import type { PivotChartSpecPipeline, VChartSpecPipeline } from 'src/types'
import {
  xBand,
  yLinear,
  initArea,
  stackInverse,
  backgroundColor,
  label,
  tooltip,
  discreteLegend,
  color,
  datasetPivot,
  pivotIndicators,
  pivotDiscreteLegend,
  pivotAdapter,
  initPivot,
  pivotIndicatorsAsRow,
  pivotGridStyle,
  pivotColumnDimensions,
  pivotRowDimensions,
  annotationPoint,
  annotationVerticalLine,
  annotationHorizontalLine,
  annotationArea,
  pointStyle,
  lineStyle,
  areaStyle,
  verticalCrosshairLine,
  pointStateDimensionHover,
  datasetXY,
  progressive,
  colorAdapter,
  linearColor,
  colorLegend,
  colorPointStyleFill,
  colorLineStyleFill,
  colorAreaStyleFill,
  pivotColorLegend,
  pivotAxisStyle,
  pivotTitle,
  splitLine,
  dimensionLinkage,
  brush,
} from '../pipes'

const area: VChartSpecPipeline = [
  initArea,
  stackInverse,
  colorAdapter(color, linearColor),
  backgroundColor,
  datasetXY,
  progressive,
  xBand,
  yLinear,
  label,
  brush,
  tooltip,
  colorAdapter(discreteLegend, colorLegend),
  verticalCrosshairLine,
  colorPointStyleFill(pointStyle),
  pointStateDimensionHover,
  colorLineStyleFill(lineStyle),
  colorAreaStyleFill(areaStyle),
  annotationPoint,
  annotationVerticalLine,
  annotationHorizontalLine,
  annotationArea,
  splitLine,
]

const pivotArea: PivotChartSpecPipeline = [
  initPivot,
  pivotGridStyle,
  pivotIndicatorsAsRow,
  datasetPivot,
  pivotIndicators([
    initArea,
    colorAdapter(color, linearColor),
    backgroundColor,
    stackInverse,
    datasetXY,
    progressive,
    xBand,
    pivotAxisStyle(yLinear),
    label,
    brush,
    tooltip,
    verticalCrosshairLine,
    colorPointStyleFill(pointStyle),
    pointStateDimensionHover,
    colorLineStyleFill(lineStyle),
    colorAreaStyleFill(areaStyle),
    annotationPoint,
    annotationVerticalLine,
    annotationHorizontalLine,
    annotationArea,
    splitLine,
  ]),
  pivotRowDimensions,
  pivotColumnDimensions,
  pivotTitle,
  colorAdapter(pivotDiscreteLegend, pivotColorLegend),
  dimensionLinkage,
]

export const areaSpecPipeline = [pivotAdapter(area, pivotArea)]
