import type { PivotChartSpecPipeline, VChartSpecPipeline } from 'src/types'
import {
  initBar,
  datasetYX,
  xLinear,
  yBand,
  backgroundColor,
  label,
  tooltip,
  discreteLegend,
  color,
  pivotAdapter,
  initPivot,
  datasetPivot,
  pivotIndicators,
  pivotDiscreteLegend,
  pivotIndicatorsAsCol,
  pivotGridStyle,
  pivotColumnDimensions,
  pivotRowDimensions,
  barStyle,
  annotationPoint,
  annotationVerticalLine,
  annotationHorizontalLine,
  annotationAreaBand,
  horizontalCrosshairRect,
  stackCornerRadius,
  progressive,
  colorAdapter,
  linearColor,
  colorLegend,
  colorBarStyleFill,
  pivotColorLegend,
  barMaxWidth,
  pivotAxisStyle,
  pivotTitle,
  dimensionLinkage,
  brush,
  isPlayer,
  playerYX,
  playerYBand,
  playerXLinear,
} from '../pipes'
import { condition } from '../utils'

const bar: VChartSpecPipeline = [
  initBar,
  stackCornerRadius,
  barMaxWidth,
  colorAdapter(color, linearColor),
  backgroundColor,
  condition(isPlayer, playerYX, datasetYX),
  progressive,
  condition(isPlayer, playerXLinear, xLinear),
  condition(isPlayer, playerYBand, yBand),

  label,
  brush,
  tooltip,
  colorAdapter(discreteLegend, colorLegend),
  horizontalCrosshairRect,
  colorBarStyleFill(barStyle),
  annotationPoint,
  annotationVerticalLine,
  annotationHorizontalLine,
  annotationAreaBand,
]

const pivotBar: PivotChartSpecPipeline = [
  initPivot,
  pivotGridStyle,
  pivotIndicatorsAsCol,
  datasetPivot,
  pivotIndicators([
    initBar,
    stackCornerRadius,
    barMaxWidth,
    colorAdapter(color, linearColor),
    backgroundColor,
    datasetYX,
    progressive,
    xLinear,
    pivotAxisStyle(yBand),
    label,
    brush,
    tooltip,
    colorBarStyleFill(barStyle),
    horizontalCrosshairRect,
    annotationPoint,
    annotationVerticalLine,
    annotationHorizontalLine,
    annotationAreaBand,
  ]),
  pivotRowDimensions,
  pivotColumnDimensions,
  pivotTitle,
  colorAdapter(pivotDiscreteLegend, pivotColorLegend),
  dimensionLinkage,
]

export const barSpecPipeline = [pivotAdapter(bar, pivotBar)]
