import type { PivotChartSpecPipeline, VChartSpecPipeline } from 'src/types'
import {
  initColumn,
  datasetXY,
  xBand,
  yLinear,
  percent,
  backgroundColor,
  label,
  tooltip,
  discreteLegend,
  color,
  pivotAdapter,
  initPivot,
  datasetPivot,
  pivotIndicators,
  pivotDiscreteLegend,
  pivotIndicatorsAsRow,
  pivotGridStyle,
  pivotRowDimensions,
  pivotColumnDimensions,
  stackInverse,
  barStyle,
  annotationPoint,
  annotationVerticalLine,
  annotationHorizontalLine,
  annotationAreaBand,
  verticalCrosshairRect,
  stackCornerRadius,
  progressive,
  colorAdapter,
  linearColor,
  colorLegend,
  colorBarStyleFill,
  pivotColorLegend,
  barMaxWidth,
  pivotAxisStyle,
  pivotTitle,
  dimensionLinkage,
  brush,
} from '../pipes'

const columnPercent: VChartSpecPipeline = [
  initColumn,
  stackCornerRadius,
  stackInverse,
  barMaxWidth,
  colorAdapter(color, linearColor),
  backgroundColor,
  percent,
  datasetXY,
  progressive,
  xBand,
  yLinear,
  label,
  brush,
  tooltip,
  colorAdapter(discreteLegend, colorLegend),
  verticalCrosshairRect,
  colorBarStyleFill(barStyle),
  annotationPoint,
  annotationVerticalLine,
  annotationHorizontalLine,
  annotationAreaBand,
]

const pivotColumnPercent: PivotChartSpecPipeline = [
  initPivot,
  pivotGridStyle,
  pivotIndicatorsAsRow,
  datasetPivot,
  pivotIndicators([
    initColumn,
    stackCornerRadius,
    stackInverse,
    barMaxWidth,
    colorAdapter(color, linearColor),
    percent,
    backgroundColor,
    datasetXY,
    progressive,
    xBand,
    pivotAxisStyle(yLinear),
    brush,
    label,
    tooltip,
    verticalCrosshairRect,
    colorBarStyleFill(barStyle),
    annotationPoint,
    annotationVerticalLine,
    annotationHorizontalLine,
    annotationAreaBand,
  ]),
  pivotRowDimensions,
  pivotColumnDimensions,
  pivotTitle,
  colorAdapter(pivotDiscreteLegend, pivotColorLegend),
  dimensionLinkage,
]

export const columnPercentSpecPipeline = [pivotAdapter(columnPercent, pivotColumnPercent)]
