import type { PivotChartSpecPipeline, VChartSpecPipeline } from 'src/types'
import {
  backgroundColor,
  color,
  datasetXY,
  datasetPivot,
  initDonut,
  initPivot,
  discreteLegend,
  pivotAdapter,
  pivotColumnDimensions,
  pivotGridStyle,
  pivotIndicators,
  pivotIndicatorsAsRow,
  pivotDiscreteLegend,
  pivotRowDimensions,
  tooltip,
  annotationPoint,
  annotationVerticalLine,
  annotationHorizontalLine,
  annotationArea,
  progressive,
  colorAdapter,
  linearColor,
  colorLegend,
  pivotColorLegend,
  pieStyle,
  colorPieStyleFill,
  labelPie,
  pivotHideIndicatorName,
  pivotTitle,
  addRegionPadding,
  brush,
  dimensionLinkage,
} from '../pipes'

const donut: VChartSpecPipeline = [
  initDonut,
  colorAdapter(color, linearColor),
  backgroundColor,
  datasetXY,
  progressive,
  brush,
  labelPie,
  colorPieStyleFill(pieStyle),
  colorAdapter(discreteLegend, colorLegend),
  tooltip,
  annotationPoint,
  annotationVerticalLine,
  annotationHorizontalLine,
  annotationArea,
]

const pivotDonut: PivotChartSpecPipeline = [
  initPivot,
  pivotGridStyle,
  pivotIndicatorsAsRow,
  pivotHideIndicatorName,
  datasetPivot,
  pivotIndicators([
    initDonut,
    addRegionPadding,
    colorAdapter(color, linearColor),
    backgroundColor,
    datasetXY,
    progressive,
    brush,
    labelPie,
    colorPieStyleFill(pieStyle),
    tooltip,
    annotationPoint,
    annotationVerticalLine,
    annotationHorizontalLine,
    annotationArea,
  ]),
  pivotRowDimensions,
  pivotColumnDimensions,
  pivotTitle,
  colorAdapter(pivotDiscreteLegend, pivotColorLegend),
  dimensionLinkage,
]

export const donutSpecPipeline = [pivotAdapter(donut, pivotDonut)]
