import type { PivotChartSpecPipeline, VChartSpecPipeline } from 'src/types'
import {
  datasetXY,
  xBand,
  yLinear,
  initLine,
  backgroundColor,
  label,
  tooltip,
  discreteLegend,
  color,
  initPivot,
  datasetPivot,
  pivotDiscreteLegend,
  pivotIndicators,
  pivotAdapter,
  pivotIndicatorsAsRow,
  pivotGridStyle,
  pivotColumnDimensions,
  pivotRowDimensions,
  annotationPoint,
  annotationVerticalLine,
  annotationHorizontalLine,
  annotationArea,
  pointStyle,
  lineStyle,
  verticalCrosshairLine,
  pointStateDimensionHover,
  progressive,
  colorAdapter,
  linearColor,
  colorLegend,
  colorLineStyleFill,
  colorPointStyleFill,
  pivotColorLegend,
  pivotTitle,
  pivotAxisStyle,
  splitLine,
  dimensionLinkage,
  brush,
} from '../pipes'

const line: VChartSpecPipeline = [
  initLine,
  colorAdapter(color, linearColor),
  backgroundColor,
  datasetXY,
  progressive,
  xBand,
  yLinear,
  brush,
  verticalCrosshairLine,
  colorAdapter(discreteLegend, colorLegend),
  colorPointStyleFill(pointStyle),
  pointStateDimensionHover,
  colorLineStyleFill(lineStyle),
  label,
  tooltip,
  annotationPoint,
  annotationVerticalLine,
  annotationHorizontalLine,
  annotationArea,
  splitLine,
]

const pivotLine: PivotChartSpecPipeline = [
  initPivot,
  pivotGridStyle,
  pivotIndicatorsAsRow,
  datasetPivot,
  pivotIndicators([
    initLine,
    colorAdapter(color, linearColor),
    backgroundColor,
    datasetXY,
    progressive,
    xBand,
    pivotAxisStyle(yLinear),
    brush,
    verticalCrosshairLine,
    colorPointStyleFill(pointStyle),
    pointStateDimensionHover,
    colorLineStyleFill(lineStyle),
    label,
    tooltip,
    annotationPoint,
    annotationVerticalLine,
    annotationHorizontalLine,
    annotationArea,
    splitLine,
  ]),
  pivotRowDimensions,
  pivotColumnDimensions,
  pivotTitle,
  colorAdapter(pivotDiscreteLegend, pivotColorLegend),
  dimensionLinkage,
]

export const lineSpecPipeline = [pivotAdapter(line, pivotLine)]
