import type { VChartSpecPipeline } from 'src/types'
import {
  initColumn,
  stackCornerRadius,
  barMaxWidth,
  colorAdapter,
  color,
  linearColor,
  backgroundColor,
  playerXY,
  progressive,
  playerXBand,
  playerYLinear,
  label,
  brush,
  tooltip,
  discreteLegend,
  colorLegend,
  horizontalCrosshairRect,
  colorBarStyleFill,
  barStyle,
  annotationPoint,
  annotationVerticalLine,
  annotationHorizontalLine,
  annotationAreaBand,
} from '../pipes'

const raceColumn: VChartSpecPipeline = [
  initColumn,
  stackCornerRadius,
  barMaxWidth,
  colorAdapter(color, linearColor),
  backgroundColor,
  playerXY,
  progressive,
  playerXBand,
  playerYLinear,

  label,
  brush,
  tooltip,
  colorAdapter(discreteLegend, colorLegend),
  horizontalCrosshairRect,
  colorBarStyleFill(barStyle),
  annotationPoint,
  annotationVerticalLine,
  annotationHorizontalLine,
  annotationAreaBand,
]

export const raceColumnSpecPipeline = raceColumn
