import type { VChartSpecPipeline } from 'src/types'
import {
  initScatter,
  colorAdapter,
  color,
  linearColor,
  backgroundColor,
  progressive,
  brush,
  discreteLegend,
  colorLegend,
  verticalCrosshairLine,
  colorPointStyleFill,
  pointStyle,
  annotationPoint,
  annotationVerticalLine,
  annotationHorizontalLine,
  playerYY,
  xLinear,
  yLinear,
  scatterSize,
  labelScatter,
  tooltipScatter,
  horizontalCrosshairLine,
  pointStateHover,
  annotationArea,
  linearRegressionLine,
  lowessRegressionLine,
  polynomialRegressionLine,
  logisticRegressionLine,
} from '../pipes'
const raceScatter: VChartSpecPipeline = [
  initScatter,
  colorAdapter(color, linearColor),
  backgroundColor,
  playerYY,
  progressive,
  xLinear,
  yLinear,
  brush,
  scatterSize,
  labelScatter,
  tooltipScatter,
  colorAdapter(discreteLegend, colorLegend),
  verticalCrosshairLine,
  horizontalCrosshairLine,
  colorPointStyleFill(pointStyle),
  pointStateHover,
  annotationPoint,
  annotationVerticalLine,
  annotationHorizontalLine,
  annotationArea,
  linearRegressionLine,
  lowessRegressionLine,
  polynomialRegressionLine,
  logisticRegressionLine,
]

export const raceScatterSpecPipeline = raceScatter
