import type { VChartSpecPipeline } from 'src/types'
import {
  initLine,
  backgroundColor,
  label,
  tooltip,
  discreteLegend,
  color,
  lineStyle,
  annotationVerticalLine,
  annotationHorizontalLine,
  verticalCrosshairLine,
  progressive,
  colorAdapter,
  linearColor,
  colorLegend,
  brush,
  xBand,
  yLinear,
  colorLineStyleFill,
  annotationArea,
  splitLine,
  playerLine,
  annotationPoint,
} from '../pipes'

const raceLine: VChartSpecPipeline = [
  initLine,
  colorAdapter(color, linearColor),
  backgroundColor,
  playerLine,
  progressive,
  xBand,
  yLinear,
  brush,
  verticalCrosshairLine,
  colorAdapter(discreteLegend, colorLegend),
  colorLineStyleFill(lineStyle),
  label,
  tooltip,
  annotationPoint,
  annotationVerticalLine,
  annotationHorizontalLine,
  annotationArea,
  splitLine,
]

export const raceLineSpecPipeline = raceLine
