import type { PivotChartSpecPipeline, VChartSpecPipeline } from 'src/types'
import {
  datasetXY,
  backgroundColor,
  tooltip,
  discreteLegend,
  color,
  pivotIndicators,
  initPivot,
  datasetPivot,
  pivotAdapter,
  pivotDiscreteLegend,
  pivotIndicatorsAsRow,
  pivotGridStyle,
  pivotRowDimensions,
  pivotColumnDimensions,
  annotationPoint,
  annotationVerticalLine,
  annotationHorizontalLine,
  annotationAreaBand,
  verticalCrosshairRect,
  stackCornerRadius,
  initRoseParallel,
  radiusAxis,
  progressive,
  pivotColorLegend,
  colorAdapter,
  linearColor,
  colorLegend,
  roseStyle,
  colorRoseStyleFill,
  labelPie,
  pivotHideIndicatorName,
  pivotTitle,
  addRegionPadding,
  dimensionLinkage,
} from '../pipes'

const roseParallel: VChartSpecPipeline = [
  initRoseParallel,
  stackCornerRadius,
  colorAdapter(color, linearColor),
  backgroundColor,
  datasetXY,
  progressive,
  radiusAxis,
  colorRoseStyleFill(roseStyle),
  colorAdapter(discreteLegend, colorLegend),
  labelPie,
  tooltip,
  verticalCrosshairRect,
  annotationPoint,
  annotationVerticalLine,
  annotationHorizontalLine,
  annotationAreaBand,
]

const pivotRoseParallel: PivotChartSpecPipeline = [
  initPivot,
  pivotGridStyle,
  pivotIndicatorsAsRow,
  pivotHideIndicatorName,
  datasetPivot,
  pivotIndicators([
    initRoseParallel,
    addRegionPadding,
    stackCornerRadius,
    colorAdapter(color, linearColor),
    backgroundColor,
    datasetXY,
    progressive,
    radiusAxis,
    verticalCrosshairRect,
    colorRoseStyleFill(roseStyle),
    labelPie,
    tooltip,
    annotationPoint,
    annotationVerticalLine,
    annotationHorizontalLine,
    annotationAreaBand,
  ]),
  pivotRowDimensions,
  pivotColumnDimensions,
  pivotTitle,
  colorAdapter(pivotDiscreteLegend, pivotColorLegend),
  dimensionLinkage,
]

export const roseParallelSpecPipeline = [pivotAdapter(roseParallel, pivotRoseParallel)]
