import type { PivotChartSpecPipeline, VChartSpecPipeline } from 'src/types'
import {
  datasetXY,
  backgroundColor,
  tooltip,
  discreteLegend,
  color,
  pivotAdapter,
  initPivot,
  datasetPivot,
  pivotIndicators,
  pivotDiscreteLegend,
  pivotIndicatorsAsRow,
  pivotGridStyle,
  pivotRowDimensions,
  pivotColumnDimensions,
  stackInverse,
  verticalCrosshairRect,
  stackCornerRadius,
  initRose,
  radiusAxis,
  progressive,
  linearColor,
  colorAdapter,
  pivotColorLegend,
  colorLegend,
  roseStyle,
  colorRoseStyleFill,
  labelPie,
  pivotHideIndicatorName,
  pivotTitle,
  addRegionPadding,
  dimensionLinkage,
  fontFamilyTheme,
} from '../pipes'

const rose: VChartSpecPipeline = [
  fontFamilyTheme,
  initRose,
  stackCornerRadius,
  stackInverse,
  colorAdapter(color, linearColor),
  backgroundColor,
  datasetXY,
  progressive,
  radiusAxis,
  verticalCrosshairRect,
  colorRoseStyleFill(roseStyle),
  colorAdapter(discreteLegend, colorLegend),
  labelPie,
  tooltip({ titleEncoding: 'angle' }),
]

const pivotRose: PivotChartSpecPipeline = [
  initPivot,
  pivotGridStyle,
  pivotIndicatorsAsRow,
  pivotHideIndicatorName,
  datasetPivot,
  pivotIndicators([
    fontFamilyTheme,
    initRose,
    addRegionPadding,
    stackCornerRadius,
    stackInverse,
    colorAdapter(color, linearColor),
    backgroundColor,
    datasetXY,
    progressive,
    radiusAxis,
    verticalCrosshairRect,
    colorRoseStyleFill(roseStyle),
    labelPie,
    tooltip({ titleEncoding: 'angle' }),
  ]),
  pivotRowDimensions,
  pivotColumnDimensions,
  pivotTitle,
  colorAdapter(pivotDiscreteLegend, pivotColorLegend),
  dimensionLinkage,
]

export const roseSpecPipeline = [pivotAdapter(rose, pivotRose)]
