import type { PivotChartSpecPipeline, VChartSpecPipeline } from 'src/types'
import {
  yLinear,
  backgroundColor,
  tooltipScatter,
  discreteLegend,
  color,
  initPivot,
  datasetPivot,
  pivotDiscreteLegend,
  pivotIndicators,
  pivotAdapter,
  pivotIndicatorsAsRow,
  pivotGridStyle,
  pivotColumnDimensions,
  pivotRowDimensions,
  annotationPoint,
  annotationVerticalLine,
  annotationHorizontalLine,
  annotationArea,
  pointStyle,
  verticalCrosshairLine,
  xLinear,
  horizontalCrosshairLine,
  pointStateHover,
  initScatter,
  progressive,
  datasetScatter,
  linearColor,
  colorAdapter,
  colorPointStyleFill,
  colorLegend,
  pivotColorLegend,
  labelScatter,
  scatterSize,
  linearRegressionLine,
  lowessRegressionLine,
  polynomialRegressionLine,
  logisticRegressionLine,
  pivotAxisStyle,
  pivotTitle,
  dimensionLinkage,
  brush,
} from '../pipes'

const scatter: VChartSpecPipeline = [
  initScatter,
  colorAdapter(color, linearColor),
  backgroundColor,
  datasetScatter,
  progressive,
  xLinear,
  yLinear,
  brush,
  scatterSize,
  labelScatter,
  tooltipScatter,
  colorAdapter(discreteLegend, colorLegend),
  verticalCrosshairLine,
  horizontalCrosshairLine,
  colorPointStyleFill(pointStyle),
  pointStateHover,
  annotationPoint,
  annotationVerticalLine,
  annotationHorizontalLine,
  annotationArea,
  linearRegressionLine,
  lowessRegressionLine,
  polynomialRegressionLine,
  logisticRegressionLine,
]

const pivotScatter: PivotChartSpecPipeline = [
  initPivot,
  pivotGridStyle,
  pivotIndicatorsAsRow,
  datasetPivot,
  pivotIndicators([
    initScatter,
    colorAdapter(color, linearColor),
    backgroundColor,
    datasetScatter,
    progressive,
    xLinear,
    pivotAxisStyle(yLinear),
    brush,
    scatterSize,
    labelScatter,
    tooltipScatter,
    verticalCrosshairLine,
    horizontalCrosshairLine,
    colorPointStyleFill(pointStyle),
    pointStateHover,
    annotationPoint,
    annotationVerticalLine,
    annotationHorizontalLine,
    annotationArea,
    linearRegressionLine,
    lowessRegressionLine,
    polynomialRegressionLine,
    logisticRegressionLine,
  ]),
  pivotRowDimensions,
  pivotColumnDimensions,
  pivotTitle,
  colorAdapter(pivotDiscreteLegend, pivotColorLegend),
  dimensionLinkage,
]

export const scatterSpecPipeline = [pivotAdapter(scatter, pivotScatter)]
