// table
export { registerTable } from './table'
export { registerPivotTable } from './pivotTable'
// cartesian
export { registerLine } from './line'
export { registerColumn } from './column'
export { registerColumnParallel } from './columnParallel'
export { registerColumnPercent } from './columnPercent'
export { registerBar } from './bar'
export { registerRaceBar } from './raceBar'
export { registerRaceColumn } from './raceColumn'
export { registerRaceScatter } from './raceScatter'
export { registerRaceLine } from './raceLine'
export { registerRacePie } from './racePie'
export { registerRaceDonut } from './raceDonut'
export { registerBarPercent } from './barPercent'
export { registerBarParallel } from './barParallel'
export { registerArea } from './area'
export { registerAreaPercent } from './areaPercent'
export { registerScatter } from './scatter'
export { registerDualAxis } from './dualAxis'
// polar
export { registerPie } from './pie'
export { registerDonut } from './donut'
export { registerRose } from './rose'
export { registerRoseParallel } from './roseParallel'
export { registerRadar } from './radar'
// other
export { registerHeatmap } from './heatmap'
export { registerFunnel } from './funnel'
export { registerBoxPlot } from './boxplot'
export { registerHistogram } from './histogram'

// hierarchy
export { registerTreeMap } from './treeMap'
export { registerSunburst } from './sunburst'
export { registerCirclePacking } from './circlePacking'
