version: '3.8'

services:
  vbi_fe:
    build:
      context: ..
      dockerfile: docker/vbi_fe/Dockerfile
    ports:
      - '3000:80'
    depends_on:
      - vbi_be
    restart: unless-stopped
    networks:
      - vbi_net

  vbi_be:
    build:
      context: ..
      dockerfile: docker/vbi_be/Dockerfile
    ports:
      - '3030:3030'
      - '9229:9229'
      - '1234:1234'
    env_file:
      - ../.env
    environment:
      - NODE_ENV=production
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - vbi_net

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    env_file:
      - ../.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5454:5454'
    networks:
      - vbi_net

volumes:
  postgres_data:

networks:
  vbi_net:
