name: Bug Server CI

# 这里业务方根据需求设置
on:
  pull_request:
    branches: ['main']
    types: [opened, synchronize, reopened]
    paths:
      - 'packages/vseed/**'
  push:
    branches: ['main']
    paths:
      - 'packages/vseed/**'

env:
  CI: true
  HUSKY: 0

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUG_SERVER_TOKEN: ${{ secrets.BUG_SERVER_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup environment file
        run: cp .env.example .env

      - name: Setup pnpm
        uses: pnpm/action-setup@1e1c8eafbd745f64b1ef30a7d7ed7965034c486c # v4.2.0
        with:
          cache: true

      - name: Setup Node
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: 24

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Print All Github Environment Variables
        run: env

      - name: Build
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'
        run: pnpm --filter '!website' build

      - name: Run CI
        if: ${{ env.BUG_SERVER_TOKEN != '' }}
        working-directory: ./tools/bugserver-trigger
        run: pnpm run ci

      - name: Skip Bug Server CI
        if: ${{ env.BUG_SERVER_TOKEN == '' }}
        run: echo "BUG_SERVER_TOKEN is empty. Skip bug server trigger."
